In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('../Material/test.csv')
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011


In [36]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011


In [37]:
df.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
35,36,KHOA TRINH,ELECTRONIC MAINTENANCE TECHNICIAN,101953.20,139102.95,16483.94,NaN,257540.09,257540.09,2011
36,37,SUSAN CURRIN,"ADMINISTRATOR, SFGH MEDICAL CENTER",245124.44,0.00,12000.00,NaN,257124.44,257124.44,2011
37,38,JAMES BOSCH,"INSPECTOR III, (POLICE DEPARTMENT)",110661.20,31162.04,111446.20,NaN,253269.44,253269.44,2011
38,39,JONES WONG,LIEUTENANT III (POLICE DEPARTMENT),132202.26,52648.92,67083.83,NaN,251935.01,251935.01,2011
39,40,BRENDAN WARD,"BATTALION CHIEF, (FIRE DEPARTMENT)",147158.85,64985.85,39540.46,NaN,251685.16,251685.16,2011


In [38]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)

s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [39]:
data = [[1,444, 'abc' ],
[2,555,'def'],
[3,666, 'ghi'],
[4,777, 'xyz' ] ]
df = pd.DataFrame(data, columns=["idx","id","name"])
df

,idx,id,name
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,777,xyz


In [40]:
df.dtypes

idx      int64
id       int64
name    object
dtype: object

In [41]:
df['id'].dtype

dtype('int64')

In [42]:
df['id' ] = df['id' ].astype("category")
df.dtypes

idx        int64
id      category
name      object
dtype: object

In [43]:
cat_cols = ['idx', 'name' ]
num_cols = ['id']
df[cat_cols] = df[cat_cols].astype("category")

df.dtypes

idx     category
id      category
name    category
dtype: object

In [44]:
df.describe()

,idx,id,name
count,4,4,4
unique,4,4,4
top,1,444,abc
freq,1,1,1


In [45]:
data = [[1,444,'abc' ],
[2,555,'def'],
[3,666,'ghi' ],
[4,777, 'xyz' ]]
df = pd.DataFrame(data, columns=["idx","id","name"])
cat_cols = ['idx', 'name' ]

df[cat_cols] = df[cat_cols].astype("category")

df.describe()
df.describe(include="all")
df.describe(include="category")

,idx,name
count,4,4
unique,4,4
top,1,abc
freq,1,1


In [46]:
df['id']

0    444
1    555
2    666
3    777
Name: id, dtype: int64

In [47]:
df['id'].describe()

count      4.000000
mean     610.500000
std      143.300384
min      444.000000
25%      527.250000
50%      610.500000
75%      693.750000
max      777.000000
Name: id, dtype: float64

In [48]:
print(df['id'].unique())
print(df['id'].nunique())
print(df['id'].value_counts())

[444 555 666 777]
4
id
444    1
555    1
666    1
777    1
Name: count, dtype: int64


In [49]:
df.columns

Index(['idx', 'id', 'name'], dtype='object')

In [50]:
df['id'].mean()
df['id'].max()
df['id'].sum()

np.int64(2442)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   idx     4 non-null      category
 1   id      4 non-null      int64   
 2   name    4 non-null      category
dtypes: category(2), int64(1)
memory usage: 580.0 bytes


In [52]:
data = [[1,444,'abc' ],
[2,555,'def'],
[3,666,'ghi' ],
[4,777, 'xyz' ]]
df = pd.DataFrame(data, columns=["idx","id","name"])
df

,idx,id,name
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,777,xyz


In [53]:
df['id'].max()

np.int64(777)

In [54]:
df.max()

idx       4
id      777
name    xyz
dtype: object

In [55]:
df['id'].values

array([444, 555, 666, 777])

In [56]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 777, 'xyz']], dtype=object)

In [57]:
df.replace('abc', 'xyz')

,idx,id,name
0,1,444,xyz
1,2,555,def
2,3,666,ghi
3,4,777,xyz


In [58]:
df.replace({444:"Aya",777:444})

,idx,id,name
0,1,Aya,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [59]:
def duplicated(x):
    return x * 2

In [60]:
df['id'].apply(duplicated)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [61]:
df['id'].apply(lambda x : x*2)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [62]:
df.idx
df.idx.iloc[2]

np.int64(3)

In [63]:
print(df.iloc[2]) 
print(df.iloc[2,1]) 
print(df.iloc[:, 0:2]) 

idx       3
id      666
name    ghi
Name: 2, dtype: object
666
   idx   id
0    1  444
1    2  555
2    3  666
3    4  777


In [64]:
df['new_col' ] = df.name + df.name
df

,idx,id,name,new_col
0,1,444,abc,abcabc
1,2,555,def,defdef
2,3,666,ghi,ghighi
3,4,777,xyz,xyzxyz


In [65]:
null = df.isnull()
null

,idx,id,name,new_col
0,False,False,False,False
1,False,False,False,False
2,False,False,False,False
3,False,False,False,False


In [66]:
pd.DataFrame(null.sum()).T

,idx,id,name,new_col
0,0,0,0,0
